In [1]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import os

In [2]:
path = '/mnt/c/Users/koles/Downloads/datasets/zomato/'

In [3]:
!ls $path

archive.zip  food.csv  menu.csv  orders.csv  restaurant.csv  users.csv

In [4]:
files = [i for i in os.listdir(path) if not i.endswith('.zip')]
files

['food.csv', 'menu.csv', 'orders.csv', 'restaurant.csv', 'users.csv']

# 1. Обзор данных

In [551]:
# функция, которые выводит основную
# информацию про таблицу
def df_info(df: pd.DataFrame) -> None:
    display(df.head())
    display(df.info())
    display(df.describe())
    display(df.isna().sum())
    print('\nКоличество дубликатов', df.duplicated().sum())


# в цикле пройдемся по каждой таблице 
# и посмотрим на нее
dfs = []
for csv in files:
    df = pd.read_csv(path+csv)
    
    if csv == 'users.csv':
        # в данных присутствует приватная
        # информация, удалим ее
        df.drop(['email', 'password'], axis=1, inplace=True)
    
    dfs.append(df)
    print(csv)
    df_info(df)
    print('\n\n')

food.csv

   Unnamed: 0 f_id                  item veg_or_non_veg
0           0  fd0     Aloo Tikki Burger            Veg
1           1  fd1     Veg Creamy Burger            Veg
2           2  fd2   Cheese Burst Burger            Veg
3           3  fd3  Paneer Creamy Burger            Veg
4           4  fd4        Maxican Burger            Veg

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 371561 entries, 0 to 371560
Data columns (total 4 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Unnamed: 0      371561 non-null  int64
 1   f_id            371561 non-null  object
 2   item            371560 non-null  object
 3   veg_or_non_veg  371560 non-null  object
dtypes: int64(1), object(3)
memory usage: 11.3+ MB

None

          Unnamed: 0
count  371561.000000
mean   185780.000000
std    107260.566023
min         0.000000
25%     92890.000000
50%    185780.000000
75%    278670.000000
max    371560.000000

Unnamed: 0        0
f_id              0
item              1
veg_or_non_veg    1
dtype: int64

Количество дубликатов 0



menu.csv

   Unnamed: 0 menu_id    r_id      f_id           cuisine price
0           0     mn0  567335       fd0  Beverages,Pizzas  40.0
1           1     mn0  567335  fd669322  Beverages,Pizzas  40.0
2           2   mn328  158203       fd0         Beverages  65.0
3           3   mn328  158203  fd669322         Beverages  65.0
4           4   mn449  158203       fd0         Beverages  65.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1179936 entries, 0 to 1179935
Data columns (total 6 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   Unnamed: 0  1179936 non-null  int64
 1   menu_id     1179936 non-null  object
 2   r_id        1179936 non-null  int64
 3   f_id        1179936 non-null  object
 4   cuisine     1179936 non-null  object
 5   price       1179936 non-null  object
dtypes: int64(2), object(4)
memory usage: 54.0+ MB

None

         Unnamed: 0          r_id
count  1.179936e+06  1.179936e+06
mean   5.899675e+05  3.156445e+05
std    3.406183e+05  1.784361e+05
min    0.000000e+00  2.110000e+02
25%    2.949838e+05  1.321870e+05
50%    5.899675e+05  3.529850e+05
75%    8.849512e+05  4.769080e+05
max    1.179935e+06  5.806910e+05

Unnamed: 0    0
menu_id       0
r_id          0
f_id          0
cuisine       0
price         0
dtype: int64

Количество дубликатов 0



orders.csv

   Unnamed: 0  order_date  sales_qty  sales_amount currency  user_id      r_id
0           0  2017-10-10        100         41241      INR    49226  567335.0
1           1  2018-05-08          3            -1      INR    77359  531342.0
2           2  2018-04-06          1           875      INR     5321  158203.0
3           3  2018-04-11          1           583      INR    21343  187912.0
4           4  2018-06-18          6          7176      INR    75378  543530.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150281 entries, 0 to 150280
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Unnamed: 0    150281 non-null  int64
 1   order_date    150281 non-null  object
 2   sales_qty     150281 non-null  int64
 3   sales_amount  150281 non-null  int64
 4   currency      150281 non-null  object
 5   user_id       150281 non-null  int64
 6   r_id          148664 non-null  float64
dtypes: float64(1), int64(4), object(2)
memory usage: 8.0+ MB

None

,Unnamed: 0,sales_qty,sales_amount,user_id,r_id
count,150281.000000,150281.000000,1.502810e+05,150281.000000,148664.000000
mean,75140.000000,16.264997,6.564802e+03,49969.366553,363433.090513
std,43382.532239,114.761496,2.991743e+04,28902.241989,167889.871825
min,0.000000,1.000000,-1.000000e+00,1.000000,211.000000
25%,37570.000000,1.000000,1.710000e+02,24826.000000,233136.750000
50%,75140.000000,1.000000,5.090000e+02,49951.000000,412597.500000
75%,112710.000000,7.000000,3.000000e+03,75084.000000,502200.500000
max,150280.000000,14049.000000,1.510944e+06,99999.000000,581031.000000

Unnamed: 0         0
order_date         0
sales_qty          0
sales_amount       0
currency           0
user_id            0
r_id            1617
dtype: int64

Количество дубликатов 0



restaurant.csv

,Unnamed: 0,id,name,city,rating,rating_count,cost,cuisine,lic_no,link,address,menu
0,0,567335,AB FOODS POINT,Abohar,--,Too Few Ratings,₹ 200,"Beverages,Pizzas",22122652000138,https://www.swiggy.com/restaurants/ab-foods-po...,"AB FOODS POINT, NEAR RISHI NARANG DENTAL CLINI...",Menu/567335.json
1,1,531342,Janta Sweet House,Abohar,4.4,50+ ratings,₹ 200,"Sweets,Bakery",12117201000112,https://www.swiggy.com/restaurants/janta-sweet...,"Janta Sweet House, Bazar No.9, Circullar Road,...",Menu/531342.json
2,2,158203,theka coffee desi,Abohar,3.8,100+ ratings,₹ 100,Beverages,22121652000190,https://www.swiggy.com/restaurants/theka-coffe...,"theka coffee desi, sahtiya sadan road city",Menu/158203.json
3,3,187912,Singh Hut,Abohar,3.7,20+ ratings,₹ 250,"Fast Food,Indian",22119652000167,https://www.swiggy.com/restaurants/singh-hut-n...,"Singh Hut, CIRCULAR ROAD NEAR NEHRU PARK ABOHAR",Menu/187912.json
4,4,543530,GRILL MASTERS,Abohar,--,Too Few Ratings,₹ 250,"Italian-American,Fast Food",12122201000053,https://www.swiggy.com/restaurants/grill-maste...,"GRILL MASTERS, ADA Heights, Abohar - Hanumanga...",Menu/543530.json

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148541 entries, 0 to 148540
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Unnamed: 0    148541 non-null  int64
 1   id            148541 non-null  int64
 2   name          148455 non-null  object
 3   city          148541 non-null  object
 4   rating        148455 non-null  object
 5   rating_count  148455 non-null  object
 6   cost          148410 non-null  object
 7   cuisine       148442 non-null  object
 8   lic_no        148312 non-null  object
 9   link          148541 non-null  object
 10  address       148455 non-null  object
 11  menu          148541 non-null  object
dtypes: int64(2), object(10)
memory usage: 13.6+ MB

None

          Unnamed: 0             id
count  148541.000000  148541.000000
mean    74270.000000  363466.378912
std     42880.237505  167890.977174
min         0.000000     211.000000
25%     37135.000000  233320.000000
50%     74270.000000  412628.000000
75%    111405.000000  502223.000000
max    148540.000000  581031.000000

Unnamed: 0        0
id                0
name             86
city              0
rating           86
rating_count     86
cost            131
cuisine          99
lic_no          229
link              0
address          86
menu              0
dtype: int64

Количество дубликатов 0



users.csv

,Unnamed: 0,user_id,name,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size
0,0,1,Claire Ferguson,20,Female,Single,Student,No Income,Post Graduate,4
1,1,2,Jennifer Young,24,Female,Single,Student,Below Rs.10000,Graduate,3
2,2,3,Jermaine Roberson,22,Male,Single,Student,Below Rs.10000,Post Graduate,3
3,3,4,Rachel Carpenter,22,Female,Single,Student,No Income,Graduate,6
4,4,5,Shawn Parker,22,Male,Single,Student,Below Rs.10000,Post Graduate,4

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 10 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Unnamed: 0                  100000 non-null  int64
 1   user_id                     100000 non-null  int64
 2   name                        100000 non-null  object
 3   Age                         100000 non-null  int64
 4   Gender                      100000 non-null  object
 5   Marital Status              100000 non-null  object
 6   Occupation                  100000 non-null  object
 7   Monthly Income              100000 non-null  object
 8   Educational Qualifications  100000 non-null  object
 9   Family size                 100000 non-null  int64
dtypes: int64(4), object(6)
memory usage: 7.6+ MB

None

          Unnamed: 0        user_id            Age    Family size
count  100000.000000  100000.000000  100000.000000  100000.000000
mean    49999.500000   50000.500000      24.628580       3.280990
std     28867.657797   28867.657797       2.971743       1.349242
min         0.000000       1.000000      18.000000       1.000000
25%     24999.750000   25000.750000      23.000000       2.000000
50%     49999.500000   50000.500000      24.000000       3.000000
75%     74999.250000   75000.250000      26.000000       4.000000
max     99999.000000  100000.000000      33.000000       6.000000

Unnamed: 0                    0
user_id                       0
name                          0
Age                           0
Gender                        0
Marital Status                0
Occupation                    0
Monthly Income                0
Educational Qualifications    0
Family size                   0
dtype: int64

Количество дубликатов 0

### Выводы

Для анализа доступны данные приложения по доставки еды. 

Таблица Orders содержит информацию о заказах, включая дату и время заказа, количество продаж, сумму продаж, валюту, id пользователя и id ресторана.

В таблице Food хранится информация о блюдах, включая их id, название и отметка для вегетарианцев.

Таблица Menu содержит информацию о меню ресторана, включая id меню, id ресторана, id блюда, кухню и цену. 

В таблице Restaurant хранится информация о ресторанах, включая id, название, местоположение, рейтинг, количество оценок, стоимость, кухню, номер лицензии, ссылку на веб-сайт, адрес и меню. 

Таблица Users содержит информацию о пользователях приложения, включая их id, имя, возраст, пол, семейное положение, род занятий, ежемесячный доход, уровень образования и размер семьи.


#### На этапе предобработки данных нужно будет:

    food.csv
    1. убрать колонку `Unnamed: 0`
    2. в колонках `item` и `veg_or_non_veg` есть один пропуск

    menu.csv
    1. убрать колонку `Unnamed: 0`
    2. исправить тип колонки `price` на `float`

    orders.csv
    1. убрать колонку `Unnamed: 0`
    2. исправить тип колонки `order_date` на `datetime`
    3. в колонке 'r_id' присутствуют пропуски
    4. колонка `sales_qty` имеет аномально высокие значения
    5. колонка `sales_amount` имеет аномально высокие и отрицательные значения значения

    restarant.csv
    1. убрать колонку `Unnamed: 0`
    2. исправить тип колонки `cost` на `float`
    3. исправить тип колонки `rating` на `float`
    3. в колонках `name`, `rating`, `rating_count`, `cost`, `cuisine`, `lic_no`, `address` есть пропуски

    users.csv
    1. убрать колонку `Unnamed: 0`

# 2. Предобработка данных

In [507]:
# сохраним датафреймы в переменные
food, menu, orders, restarant, users = dfs

**food**

In [508]:
# удалим колонку 'Unnamed: 0' в таблице 'food'
food = food.drop('Unnamed: 0', axis=1)

In [509]:
food.head()

  f_id                  item veg_or_non_veg
0  fd0     Aloo Tikki Burger            Veg
1  fd1     Veg Creamy Burger            Veg
2  fd2   Cheese Burst Burger            Veg
3  fd3  Paneer Creamy Burger            Veg
4  fd4        Maxican Burger            Veg

**menu**

In [510]:
# удалим колонку 'Unnamed: 0' в таблице 'menu'
menu = menu.drop('Unnamed: 0', axis=1)

In [511]:
# исправим тип колонки 'price' с 'object' на 'float'

# для начала посмотрим наличеи не числовых значений
# в колонке 'price'
pd.to_numeric(menu.price, errors='coerce').isna().sum()

1193

In [512]:
# всего таких значений 1193. 

# посмотрим на уникальные не числовые значения
# в колонке `price`
menu[pd.to_numeric(menu.price, errors='coerce').isna()].price.unique()

array(['₹200 FOR TWO', '₹350 FOR TWO', '₹400 FOR TWO', '₹500 FOR TWO',
       '₹300 FOR TWO', '₹199 FOR TWO', '₹250 FOR TWO', '₹150 FOR TWO',
       '₹600 FOR TWO', '₹100 FOR TWO', '₹1200 FOR TWO', '₹60 FOR TWO',
       '₹550 FOR TWO', '₹99 FOR TWO', '₹450 FOR TWO', '₹800 FOR TWO',
       '₹280 FOR TWO', '₹700 FOR TWO', '₹130 FOR TWO', '₹70 FOR TWO',
       '₹1000 FOR TWO', '₹125 FOR TWO', '₹120 FOR TWO', '₹90 FOR TWO',
       '₹180 FOR TWO', '₹850 FOR TWO', '₹50 FOR TWO', '₹399 FOR TWO',
       '₹1245 FOR TWO', '₹900 FOR TWO', '₹299 FOR TWO', '₹1500 FOR TWO',
       '₹290 FOR TWO', '₹149 FOR TWO', '₹160 FOR TWO', '₹650 FOR TWO',
       '₹330 FOR TWO', '₹80 FOR TWO', '₹1800 FOR TWO', '₹220 FOR TWO',
       '₹110 FOR TWO', '₹460 FOR TWO', '₹5 FOR TWO', '₹170 FOR TWO'],
      dtype=object)

In [513]:
# похоже на акционное предложение
# от приложения или ресторана

# чтоб не потерять информацию об
# этом предложении, создадим колонку с
# бинарной переменной, где 1 это предложение "FOR TWO"
menu['price_for_two'] = np.zeros(menu.shape[0])
menu.loc[pd.to_numeric(menu.price, errors='coerce').isna(), 'price_for_two'] = 1
menu['price_for_two'] = menu['price_for_two'].astype('int')

In [514]:
# проверим правильность выполнених действий
menu.price_for_two.sum(), pd.to_numeric(menu.price, errors='coerce').isna().sum()

(1193, 1193)

In [515]:
# уберем знак валюты и слова "FOR TWO"
changed_price = menu[pd.to_numeric(menu.price, errors='coerce').isna()] \
                    .price.apply(lambda x: x.split()[0][1:])

# проверим правильность выполнених действий
display(changed_price.unique(), \
            menu[pd.to_numeric(menu.price, errors='coerce').isna()].price.unique())

array(['200', '350', '400', '500', '300', '199', '250', '150', '600',
       '100', '1200', '60', '550', '99', '450', '800', '280', '700',
       '130', '70', '1000', '125', '120', '90', '180', '850', '50', '399',
       '1245', '900', '299', '1500', '290', '149', '160', '650', '330',
       '80', '1800', '220', '110', '460', '5', '170'], dtype=object)

array(['₹200 FOR TWO', '₹350 FOR TWO', '₹400 FOR TWO', '₹500 FOR TWO',
       '₹300 FOR TWO', '₹199 FOR TWO', '₹250 FOR TWO', '₹150 FOR TWO',
       '₹600 FOR TWO', '₹100 FOR TWO', '₹1200 FOR TWO', '₹60 FOR TWO',
       '₹550 FOR TWO', '₹99 FOR TWO', '₹450 FOR TWO', '₹800 FOR TWO',
       '₹280 FOR TWO', '₹700 FOR TWO', '₹130 FOR TWO', '₹70 FOR TWO',
       '₹1000 FOR TWO', '₹125 FOR TWO', '₹120 FOR TWO', '₹90 FOR TWO',
       '₹180 FOR TWO', '₹850 FOR TWO', '₹50 FOR TWO', '₹399 FOR TWO',
       '₹1245 FOR TWO', '₹900 FOR TWO', '₹299 FOR TWO', '₹1500 FOR TWO',
       '₹290 FOR TWO', '₹149 FOR TWO', '₹160 FOR TWO', '₹650 FOR TWO',
       '₹330 FOR TWO', '₹80 FOR TWO', '₹1800 FOR TWO', '₹220 FOR TWO',
       '₹110 FOR TWO', '₹460 FOR TWO', '₹5 FOR TWO', '₹170 FOR TWO'],
      dtype=object)

In [516]:
# сохраним отредактированные записи
# и изменим тип переменной на `float`
menu.loc[pd.to_numeric(menu.price, errors='coerce').isna(), 'price'] = changed_price
menu['price'] = menu['price'].astype('float')

**orders**

In [517]:
# удалим колонку 'Unnamed: 0' в таблице 'orders'
orders = orders.drop('Unnamed: 0', axis=1)

In [518]:
# изменим тип колонки `order_date` на `datetime`
orders['order_date'] = pd.to_datetime(orders['order_date'])

In [519]:
# посмотрим на пропуски в колонке `r_id`
orders[orders.r_id.isna()]

       order_date  sales_qty  sales_amount currency  user_id  r_id
148664 2019-03-19          1          1625    INR\r    50862   NaN
148665 2019-03-19          1          1741    INR\r    25120   NaN
148666 2019-03-20          1          1463    INR\r    84260   NaN
148667 2019-03-20          1          2949    INR\r    14329   NaN
148668 2019-03-21          1          1241    INR\r    38858   NaN
...           ...        ...           ...      ...      ...   ...
150276 2019-04-18          1           394    INR\r    79856   NaN
150277 2019-04-23          1           667    INR\r    65798   NaN
150278 2019-04-23          1           625    INR\r    49176   NaN
150279 2019-04-24          7          8625    INR\r    87924   NaN
150280 2019-04-24          3          3792    INR\r    41474   NaN

[1617 rows x 6 columns]

In [520]:
# всего таких значений 1617 что примерно 1%

# восстановить пропуски или заменить их на
# популярные r_id среди пользователей, у которых
# есть пропуски мы не можем, поэтому оставляем как есть

In [521]:
# посмотрим на выбросы в колонке `sales_qty`
orders.sales_qty.describe()

count    150281.000000
mean         16.264997
std         114.761496
min           1.000000
25%           1.000000
50%           1.000000
75%           7.000000
max       14049.000000
Name: sales_qty, dtype: float64

In [522]:
orders.sort_values('sales_qty', ascending=False).head(20)

      order_date  sales_qty  sales_amount currency  user_id      r_id
22034 2019-11-29      14049        628657    INR\r    60046  416409.0
21805 2019-01-25      10667        534463    INR\r    78855  407770.0
21547 2018-02-08      10667        450954    INR\r    58535  385543.0
21663 2018-07-23      10667        534463    INR\r    43819  537634.0
63986 2018-01-31       8800        647778    INR\r    66926  542825.0
21313 2020-02-29       8000         38889    INR\r    97856  286268.0
21990 2019-09-30       6667        298310    INR\r    71745  493031.0
21314 2020-04-14       6000         29167    INR\r    73359  230460.0
21606 2018-05-04       5333        267231    INR\r    15848  504000.0
21593 2018-04-18       5333        267231    INR\r    69218  480220.0
21564 2018-03-15       5333        267231    INR\r    20337  457484.0
21779 2018-12-14       5333        267231    INR\r    14698  532375.0
21499 2017-12-08       5333        225477    INR\r    29292  358151.0
21969 2019-09-05       5333        267231    INR\r    58597  469185.0
21464 2017-10-30       5333        225477    INR\r    73767  244007.0
22006 2019-10-17       5333        267231    INR\r    73936  456093.0
21475 2017-11-10       5333        225477    INR\r    11486  493145.0
21318 2019-08-08       5250        126759    INR\r    11231  393841.0
21317 2018-10-19       5250        126759    INR\r    72534  392755.0
23394 2019-08-02       5207         21671    INR\r    93771  314323.0

In [523]:
q1 = orders.sales_qty.quantile(0.25)
q3 = orders.sales_qty.quantile(0.75)
iqr = q3 - q1
upper_bound = q3 + iqr * 1.5

print('Количество строк с выбросами - {:.3f}\n'
      'Количество уникальных пользователей, котрые оформили большие заказы - {:.3f}\n'.format(
            orders[orders.sales_qty > upper_bound].shape[0] / orders.shape[0],
            orders[orders.sales_qty > upper_bound]['user_id'].nunique() / orders['user_id'].nunique()
))

Количество строк с выбросами - 0.148
Количество уникальных пользователей, котрые оформили большие заказы - 0.255

In [552]:
# количество строк с аномальными значениями в
# колонке `sales_qty` достигает 14.8%,
# каждый четвертый пользователь
# делал большоке количество заказов

In [525]:
# посмотрим на значения меньше,
# либо равные нулю в колонке `sales_amount`

orders[orders.sales_amount <= 0]

       order_date  sales_qty  sales_amount currency  user_id      r_id
1      2018-05-08          3            -1      INR    77359  531342.0
159    2018-05-26          1             0      INR    59836  102582.0
196    2019-04-30          1             0      INR    95267  553404.0
239    2018-12-28          1             0      INR    14159  499377.0
282    2018-05-08          3            -1    INR\r      357  509389.0
...           ...        ...           ...      ...      ...       ...
148969 2019-08-16          1             0    INR\r    13971       NaN
149017 2019-09-09          1             0    INR\r    21153       NaN
149053 2019-09-26          2             0    INR\r    17856       NaN
149164 2019-11-19          1             0    INR\r    64848       NaN
150195 2019-01-29          2             0    INR\r    59635       NaN

[1611 rows x 6 columns]

In [526]:
# если значения -1 больше похоже на ошибку в данных и их нужно удалить, то
# значения равные 0 могут быть промо акцией для привлечения пользователей

# посмотрим на количество таких строк и на количество уникальных пользователей в них
orders[orders.sales_amount == 0].shape, orders[orders.sales_amount == 0]['user_id'].nunique()

((1609, 6), 1592)

In [553]:
# гипотеза не подтвердилась, есть 17 пользователей,
# которые оформляли заказ на сумму 0 валюты больше одного раза,
# похоже на ошибку в данных, удалим эти строки

i = orders[orders.sales_amount <= 0].index
orders.drop(i, inplace=True)

In [529]:
# проверка

orders.sales_amount.describe()

count    1.486700e+05
mean     6.635939e+03
std      3.007124e+04
min      5.000000e+00
25%      1.760000e+02
50%      5.190000e+02
75%      3.065000e+03
max      1.510944e+06
Name: sales_amount, dtype: float64

In [530]:
# теперь минимальное значение равно 5

**restarant**

In [531]:
# удалим колонку 'Unnamed: 0' в таблице 'restarant'
restarant = restarant.drop('Unnamed: 0', axis=1)

In [532]:
restarant.head()

,id,name,city,rating,rating_count,cost,cuisine,lic_no,link,address,menu
0,567335,AB FOODS POINT,Abohar,--,Too Few Ratings,₹ 200,"Beverages,Pizzas",22122652000138,https://www.swiggy.com/restaurants/ab-foods-po...,"AB FOODS POINT, NEAR RISHI NARANG DENTAL CLINI...",Menu/567335.json
1,531342,Janta Sweet House,Abohar,4.4,50+ ratings,₹ 200,"Sweets,Bakery",12117201000112,https://www.swiggy.com/restaurants/janta-sweet...,"Janta Sweet House, Bazar No.9, Circullar Road,...",Menu/531342.json
2,158203,theka coffee desi,Abohar,3.8,100+ ratings,₹ 100,Beverages,22121652000190,https://www.swiggy.com/restaurants/theka-coffe...,"theka coffee desi, sahtiya sadan road city",Menu/158203.json
3,187912,Singh Hut,Abohar,3.7,20+ ratings,₹ 250,"Fast Food,Indian",22119652000167,https://www.swiggy.com/restaurants/singh-hut-n...,"Singh Hut, CIRCULAR ROAD NEAR NEHRU PARK ABOHAR",Menu/187912.json
4,543530,GRILL MASTERS,Abohar,--,Too Few Ratings,₹ 250,"Italian-American,Fast Food",12122201000053,https://www.swiggy.com/restaurants/grill-maste...,"GRILL MASTERS, ADA Heights, Abohar - Hanumanga...",Menu/543530.json

In [533]:
# изменим тип колонки 'cost' на 'float'

# сначало проверим вхождение знака валюты
# в строки, кроме Nan
restarant[~restarant.isna()].cost.str.contains('₹').all()

True

In [534]:
# теперь удалим знак валюты и
# изменим тип колонки
restarant.loc[~restarant.cost.isna(), 'cost'] = restarant[~restarant.cost.isna()].cost.apply(lambda x: x.split()[-1])
restarant['cost'] = restarant['cost'].astype('float')

In [535]:
# изменим тип колонки 'cost' на 'float'

restarant.rating.value_counts()[:5]

--     87014
4.0     6532
4.1     6296
4.2     5821
3.8     5736
Name: rating, dtype: int64

In [536]:
# у половины всех записей отсутствует оценка,
# чем-то заменить пропуск невозможно, пропустим
# эту колонку

In [537]:
restarant.isna().sum()

id                0
name             86
city              0
rating           86
rating_count     86
cost            131
cuisine          99
lic_no          229
link              0
address          86
menu              0
dtype: int64

In [542]:
restarant[~restarant.cost.isna()].cost.astype('float').describe()

count    148541.000000
mean        287.567554
std         796.380067
min           1.000000
25%         200.000000
50%         250.000000
75%         300.000000
max      300350.000000
Name: cost, dtype: float64

In [543]:
# заменим пропуски в колонка 'rating_count', 'cuisine'
# на самые популярные значения,
# в колонке 'cost', за счет небольшого количества
# больших значений, дисперсия очень большая,
# по этому пропуски заменим на медиану

In [538]:
def fill_na(df, columns):
    for col in columns:
        if df[col].dtype == 'O':
            x = df.groupby(col).count().iloc[:, 0].sort_values(ascending=False).index[0]
        elif df[col].dtype == 'float64':
            x = df[col].median()
        else:
            print(col, 'error')
            continue
        
        df[col].fillna(x, inplace=True)

In [539]:
fill_na(restarant, ['rating_count', 'cuisine', 'cost'])

In [544]:
restarant.isna().sum()

id                0
name             86
city              0
rating           86
rating_count      0
cost              0
cuisine           0
lic_no          229
link              0
address          86
menu              0
dtype: int64

**users**

In [546]:
# удалим колонку 'Unnamed: 0' в таблице 'users'
users = users.drop('Unnamed: 0', axis=1)

### Выводы

На этапе предобработки данных мы удалили лишние колонки, изменили типы колонок, заменили пропуски.